import type { Metadata } from "next";
import { Bebas_Neue, DM_Sans, Space_Mono } from "next/font/google";
import { headers } from "next/headers";
import { NavigationProgress } from "@/components/NavigationProgress";
import "./globals.css";

const headingFont = Bebas_Neue({
  weight: "400",
  variable: "--font-heading",
  subsets: ["latin"],
});

const bodyFont = DM_Sans({
  variable: "--font-body",
  subsets: ["latin"],
});

const monoFont = Space_Mono({
  weight: ["400", "700"],
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SPARK OpenMic 10 — The Stage Is Yours",
  description: "Performer registration platform for SPARK OpenMic 10th Edition.",
  icons: {
    icon: "/favicon.png",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Read the nonce generated by middleware — Next.js uses this to whitelist
  // its own hydration inline scripts under the nonce-based CSP.
  const nonce = (await headers()).get("x-nonce") ?? undefined;

  return (
    <html lang="en">
      <body className={`${headingFont.variable} ${bodyFont.variable} ${monoFont.variable} antialiased`} {...(nonce ? { "data-nonce": nonce } : {})}>
        <NavigationProgress />
        {children}
      </body>
    </html>
  );
}

